name       : perl-netaddr-ip
version    : 4.079
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/M/MI/MIKER/NetAddr-IP-4.079.tar.gz : ec5a82dfb7028bcd28bb3d569f95d87dd4166cc19867f2184ed3a59f6d6ca0e7
homepage   : https://search.cpan.org/dist/NetAddr-IP/
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Perl module to manage IP addresses and subnets
description: |
    This module provides an object-oriented abstraction on top of IP addresses or IP subnets, that allows for easy manipulations.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
